# Generated by Django 4.0 on 2021-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxPrice',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=None),
        ),
    ]
